services:

  nginx:
    build:
      args:
        - DOMAIN_NAME
      context: requirements/nginx
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_healthy # Wait for wordpress to be installed
    env_file:
      - .env
    image: nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - wp:/var/www/html

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy # Wait for the db to be reachable
    env_file:
      - .env
    image: wordpress
    restart: always
    volumes:
      - wp:/var/www/html

  mariadb:
    build:
      args:
        - DB_NAME
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_ROOT_PASSWORD
      context: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql

volumes:

  wp:
    name: "wp"
    driver_opts:
      type: none
      o: bind
      device: $VOLUME_PATH/wp
  db:
    name: "db"
    driver_opts:
      type: none
      o: bind
      device: $VOLUME_PATH/db
