services:

  nginx:
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    image: nginx
    networks:
      - inception
    ports:
      - "443:443"
    restart: always
    volumes:
      - wp:/var/www/html

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - 9000
    image: wordpress
    networks:
      - inception
    restart: always
    volumes:
      - wp:/var/www/html

  mariadb:
    build:
      context: requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    expose:
      - 3306
    image: mariadb
    networks:
      - inception
    restart: always
    volumes:
      - db:/var/lib/mysql

# Useless
networks:
  inception:
    name: inception

volumes:

  wp:
    name: "wp"
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/wp
  db:
    name: "db"
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}/db
