# A default network spanning all containers is automatically created

services:
 
  nginx:
    # The dockerfile directory
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    # Add .env file variables to the containers environment
    env_file:
      - .env
    # Image needs to have exact name
    image: nginx
    # Map host:443 to nginx's localhost:443
    ports:
      - "443:443"
    # Containers have to restart in case of a crash
    restart: always
    volumes:
      - wp:/var/www/html

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    # Allow other containers to reach at 9000. Default php-fpm port
    expose:
      - 9000
    image: wordpress
    restart: always
    volumes:
      - wp:/var/www/html

  mariadb:
    build:
      context: requirements/mariadb
      # Add build stage variables, by default taken from environment
      # .env contents are available to this file
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
    container_name: mariadb
    env_file:
      - .env
    # Default MySQL port
    expose:
      - 3306
    image: mariadb
    restart: always
    # TODO: uncomment
    # volumes:
    #   - db:/var/lib/mysql

volumes:

  wp:
    driver_opts:
      type: none
      # Mount
      o: bind
      # Where the volume is actually stored
      device: ${VOLUME_PATH}/wp
  # TODO: uncomment
  # db:
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ${VOLUME_PATH}/db
