# SQL files can't read env, so we'll use a heredoc

mariadb << EOF
	SET PASSWORD FOR "root"@"localhost" = PASSWORD("$MYSQL_ROOT_PASSWORD");
	CREATE DATABASE IF NOT EXISTS $DB_NAME;
	CREATE OR REPLACE USER "$MYSQL_USER"@"%" IDENTIFIED BY "$MYSQL_PASSWORD"; 
	GRANT ALL ON $DB_NAME.* TO "$MYSQL_USER"@"%";
	FLUSH PRIVILEGES;
EOF
